export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const GET_ROWS_LOADING = 'GET_ROWS_LOADING';
export const GET_ROWS_SUCCESS = 'GET_ROWS_SUCCESS';
export const GET_ROWS_ERROR = 'GET_ROWS_ERROR';